services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin_password
      DB_VENDOR: h2
    command:
      - start-dev
    ports:
      - "8080:8080"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: "uv run example.py"
    volumes:
      - ./:/app:cached
      - venv_data:/app/.venv
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/mydb
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9000:80"
    networks:
      - app-network
    depends_on:
      - app

volumes:
  postgres_data:
  venv_data:

networks:
  app-network:
    driver: bridge
