name: Publish and Release

on:
  workflow_run:
    workflows: ["Determine Next Version and Tag"]
    types:
      - completed

jobs:
  publish:
    name: Publish and Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rye
        run: |
          curl -sSf https://rye.astral.sh/get | bash
          echo "$HOME/.rye/shims" >> $GITHUB_PATH
        env:
          RYE_VERSION: "0.37.0"
          RYE_INSTALL_OPTION: "--yes"

      - name: Generate Release Notes
        run: |
          sudo apt-get install python3-pip
          python ci/generate_release_notes.py

      - name: Create GitHub Release
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "tag_name": "'"$VERSION"'",
              "target_commitish": "'"$GITHUB_SHA"'",
              "name": "'"$VERSION"'",
              "body": "'"$(cat RELEASE_NOTES.md)"'",
              "draft": false,
              "prerelease": false
            }' \
            https://api.github.com/repos/${{ github.repository }}/releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PyPI
        run: |
          bash ./ci/publish-pypi
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
