name: Publish and Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish and Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rye
        run: |
          curl -sSf https://rye.astral.sh/get | bash
          echo "$HOME/.rye/shims" >> $GITHUB_PATH
        env:
          RYE_VERSION: "0.37.0"
          RYE_INSTALL_OPTION: "--yes"

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Generate Release Notes
        run: |
          sudo apt-get install python3-pip
          python generate_release_notes.py

      - name: Create GitHub Release
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          gh release create $VERSION --notes-file RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PyPI
        run: |
          bash ./bin/publish-pypi
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
